# Generated by Django 3.1.6 on 2021-04-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('batch_date', models.DateField(auto_now=True)),
                ('course_fees', models.CharField(max_length=50)),
                ('batch_status', models.CharField(choices=[('1', 'Yet to begin'), ('2', 'Ongoing'), ('3', 'Completed')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField(auto_now=True)),
                ('enquiryid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiryid', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=50)),
                ('collegename', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enquirydate', models.DateField(auto_now=True)),
                ('followup_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Call_back'), ('2', 'Admitted'), ('3', 'Cancel')], max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.course')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.course'),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50, unique=True)),
                ('enquiryid', models.CharField(max_length=50)),
                ('coursefees', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('batchcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.batch')),
            ],
        ),
    ]
