# Generated by Django 3.1.6 on 2021-04-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='batchcode',
            new_name='batch_code',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='coursefees',
            new_name='course_fees',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='enquiryid',
            new_name='enquiry_id',
        ),
    ]
